package poe.manager.entry.item;

class BaseNameExtractor {
    static String extract(String category, String name) {
        switch (category) {
            case "amulet":      return extractAmuletBase(name);
            case "ring":        return extractRingBase(name);
            case "belt":        return extractBeltBase(name);
            case "jewel":       return extractJewelBase(name);

            case "chest":       return extractChestBase(name);
            case "boots":       return extractBootsBase(name);
            case "gloves":      return extractGlovesBase(name);
            case "helmet":      return extractHelmetBase(name);
            case "shield":      return extractShieldBase(name);
            case "quiver":      return extractQuiverBase(name);

            case "claw":        return extractClawBase(name);
            case "dagger":      return extractDaggerBase(name);
            case "oneaxe":      return extractOneaxeBase(name);
            case "onemace":     return extractOnemaceBase(name);
            case "onesword":    return extractOneswordBase(name);
            case "twoaxe":      return extractTwoaxeBase(name);
            case "twomace":     return extractTwomaceBase(name);
            case "twosword":    return extractTwoswordBase(name);
            case "sceptre":     return extractSceptreBase(name);
            case "wand":        return extractWandBase(name);
            case "bow":         return extractBowBase(name);
            case "staff":       return extractStaffBase(name);
            case "rod":         return extractRodBase(name);
        }

        return null;
    }

    private static String extractAmuletBase(String name) {
        if (name.contains("Blue Pearl Amulet")) return "Blue Pearl Amulet";
        if (name.contains("Marble Amulet"))     return "Marble Amulet";
        if (name.contains("Jet Amulet"))        return "Jet Amulet";
        if (name.contains("Paua Amulet"))       return "Paua Amulet";
        if (name.contains("Citrine Amulet"))    return "Citrine Amulet";
        if (name.contains("Ruby Amulet"))       return "Ruby Amulet";
        if (name.contains("Coral Amulet"))      return "Coral Amulet";
        if (name.contains("Amber Amulet"))      return "Amber Amulet";
        if (name.contains("Jade Amulet"))       return "Jade Amulet";
        if (name.contains("Lapis Amulet"))      return "Lapis Amulet";
        if (name.contains("Gold Amulet"))       return "Gold Amulet";
        if (name.contains("Onyx Amulet"))       return "Onyx Amulet";
        if (name.contains("Turquoise Amulet"))  return "Turquoise Amulet";
        if (name.contains("Agate Amulet"))      return "Agate Amulet";
        return null;
    }

    private static String extractChestBase(String name) {
        if (name.contains("Golden Mantle"))          return "Golden Mantle";
        if (name.contains("Shabby Jerkin"))          return "Shabby Jerkin";
        if (name.contains("Glorious Leather"))       return "Glorious Leather";
        if (name.contains("Coronal Leather"))        return "Coronal Leather";
        if (name.contains("Cutthroat's Garb"))       return "Cutthroat's Garb";
        if (name.contains("Sharkskin Tunic"))        return "Sharkskin Tunic";
        if (name.contains("Destiny Leather"))        return "Destiny Leather";
        if (name.contains("Exquisite Leather"))      return "Exquisite Leather";
        if (name.contains("Zodiac Leather"))         return "Zodiac Leather";
        if (name.contains("Assassin's Garb"))        return "Assassin's Garb";
        if (name.contains("Strapped Leather"))       return "Strapped Leather";
        if (name.contains("Buckskin Tunic"))         return "Buckskin Tunic";
        if (name.contains("Wild Leather"))           return "Wild Leather";
        if (name.contains("Full Leather"))           return "Full Leather";
        if (name.contains("Sun Leather"))            return "Sun Leather";
        if (name.contains("Thief's Garb"))           return "Thief's Garb";
        if (name.contains("Eelskin Tunic"))          return "Eelskin Tunic";
        if (name.contains("Frontier Leather"))       return "Frontier Leather";
        if (name.contains("Padded Vest"))            return "Padded Vest";
        if (name.contains("Crimson Raiment"))        return "Crimson Raiment";
        if (name.contains("Lacquered Garb"))         return "Lacquered Garb";
        if (name.contains("Crypt Armour"))           return "Crypt Armour";
        if (name.contains("Sentinel Jacket"))        return "Sentinel Jacket";
        if (name.contains("Varnished Coat"))         return "Varnished Coat";
        if (name.contains("Blood Raiment"))          return "Blood Raiment";
        if (name.contains("Sadist Garb"))            return "Sadist Garb";
        if (name.contains("Carnal Armour"))          return "Carnal Armour";
        if (name.contains("Oiled Vest"))             return "Oiled Vest";
        if (name.contains("Padded Jacket"))          return "Padded Jacket";
        if (name.contains("Oiled Coat"))             return "Oiled Coat";
        if (name.contains("Scarlet Raiment"))        return "Scarlet Raiment";
        if (name.contains("Waxed Garb"))             return "Waxed Garb";
        if (name.contains("Bone Armour"))            return "Bone Armour";
        if (name.contains("Quilted Jacket"))         return "Quilted Jacket";
        if (name.contains("Sleek Coat"))             return "Sleek Coat";
        if (name.contains("Simple Robe"))            return "Simple Robe";
        if (name.contains("Conjurer's Vestment"))    return "Conjurer's Vestment";
        if (name.contains("Spidersilk Robe"))        return "Spidersilk Robe";
        if (name.contains("Destroyer Regalia"))      return "Destroyer Regalia";
        if (name.contains("Savant's Robe"))          return "Savant's Robe";
        if (name.contains("Necromancer Silks"))      return "Necromancer Silks";
        if (name.contains("Occultist's Vestment"))   return "Occultist's Vestment";
        if (name.contains("Widowsilk Robe"))         return "Widowsilk Robe";
        if (name.contains("Vaal Regalia"))           return "Vaal Regalia";
        if (name.contains("Silken Vest"))            return "Silken Vest";
        if (name.contains("Scholar's Robe"))         return "Scholar's Robe";
        if (name.contains("Silken Garb"))            return "Silken Garb";
        if (name.contains("Mage's Vestment"))        return "Mage's Vestment";
        if (name.contains("Silk Robe"))              return "Silk Robe";
        if (name.contains("Cabalist Regalia"))       return "Cabalist Regalia";
        if (name.contains("Sage's Robe"))            return "Sage's Robe";
        if (name.contains("Silken Wrap"))            return "Silken Wrap";
        if (name.contains("Plate Vest"))             return "Plate Vest";
        if (name.contains("Sun Plate"))              return "Sun Plate";
        if (name.contains("Colosseum Plate"))        return "Colosseum Plate";
        if (name.contains("Majestic Plate"))         return "Majestic Plate";
        if (name.contains("Golden Plate"))           return "Golden Plate";
        if (name.contains("Crusader Plate"))         return "Crusader Plate";
        if (name.contains("Astral Plate"))           return "Astral Plate";
        if (name.contains("Gladiator Plate"))        return "Gladiator Plate";
        if (name.contains("Glorious Plate"))         return "Glorious Plate";
        if (name.contains("Chestplate"))             return "Chestplate";
        if (name.contains("Copper Plate"))           return "Copper Plate";
        if (name.contains("War Plate"))              return "War Plate";
        if (name.contains("Full Plate"))             return "Full Plate";
        if (name.contains("Arena Plate"))            return "Arena Plate";
        if (name.contains("Lordly Plate"))           return "Lordly Plate";
        if (name.contains("Bronze Plate"))           return "Bronze Plate";
        if (name.contains("Battle Plate"))           return "Battle Plate";
        if (name.contains("Scale Vest"))             return "Scale Vest";
        if (name.contains("Full Wyrmscale"))         return "Full Wyrmscale";
        if (name.contains("Commander's Brigandine")) return "Commander's Brigandine";
        if (name.contains("Battle Lamellar"))        return "Battle Lamellar";
        if (name.contains("Dragonscale Doublet"))    return "Dragonscale Doublet";
        if (name.contains("Desert Brigandine"))      return "Desert Brigandine";
        if (name.contains("Full Dragonscale"))       return "Full Dragonscale";
        if (name.contains("General's Brigandine"))   return "General's Brigandine";
        if (name.contains("Triumphant Lamellar"))    return "Triumphant Lamellar";
        if (name.contains("Light Brigandine"))       return "Light Brigandine";
        if (name.contains("Scale Doublet"))          return "Scale Doublet";
        if (name.contains("Infantry Brigandine"))    return "Infantry Brigandine";
        if (name.contains("Full Scale Armour"))      return "Full Scale Armour";
        if (name.contains("Soldier's Brigandine"))   return "Soldier's Brigandine";
        if (name.contains("Field Lamellar"))         return "Field Lamellar";
        if (name.contains("Wyrmscale Doublet"))      return "Wyrmscale Doublet";
        if (name.contains("Hussar Brigandine"))      return "Hussar Brigandine";
        if (name.contains("Sacrificial Garb"))       return "Sacrificial Garb";
        if (name.contains("Chainmail Vest"))         return "Chainmail Vest";
        if (name.contains("Ornate Ringmail"))        return "Ornate Ringmail";
        if (name.contains("Chain Hauberk"))          return "Chain Hauberk";
        if (name.contains("Devout Chainmail"))       return "Devout Chainmail";
        if (name.contains("Loricated Ringmail"))     return "Loricated Ringmail";
        if (name.contains("Conquest Chainmail"))     return "Conquest Chainmail";
        if (name.contains("Elegant Ringmail"))       return "Elegant Ringmail";
        if (name.contains("Saint's Hauberk"))        return "Saint's Hauberk";
        if (name.contains("Saintly Chainmail"))      return "Saintly Chainmail";
        if (name.contains("Chainmail Tunic"))        return "Chainmail Tunic";
        if (name.contains("Ringmail Coat"))          return "Ringmail Coat";
        if (name.contains("Chainmail Doublet"))      return "Chainmail Doublet";
        if (name.contains("Full Ringmail"))          return "Full Ringmail";
        if (name.contains("Full Chainmail"))         return "Full Chainmail";
        if (name.contains("Holy Chainmail"))         return "Holy Chainmail";
        if (name.contains("Latticed Ringmail"))      return "Latticed Ringmail";
        if (name.contains("Crusader Chainmail"))     return "Crusader Chainmail";
        if (name.contains("Kaom's Plate"))           return "Kaom's Plate";
        return null;
    }

    private static String extractBootsBase(String name) {
        if (name.contains("Two-Toned Boots"))    return "Two-Toned Boots";
        if (name.contains("Golden Caligae"))     return "Golden Caligae";
        if (name.contains("Avian Slippers"))     return "Avian Slippers";
        if (name.contains("Rawhide Boots"))      return "Rawhide Boots";
        if (name.contains("Goathide Boots"))     return "Goathide Boots";
        if (name.contains("Deerskin Boots"))     return "Deerskin Boots";
        if (name.contains("Nubuck Boots"))       return "Nubuck Boots";
        if (name.contains("Eelskin Boots"))      return "Eelskin Boots";
        if (name.contains("Sharkskin Boots"))    return "Sharkskin Boots";
        if (name.contains("Shagreen Boots"))     return "Shagreen Boots";
        if (name.contains("Stealth Boots"))      return "Stealth Boots";
        if (name.contains("Slink Boots"))        return "Slink Boots";
        if (name.contains("Wrapped Boots"))      return "Wrapped Boots";
        if (name.contains("Strapped Boots"))     return "Strapped Boots";
        if (name.contains("Clasped Boots"))      return "Clasped Boots";
        if (name.contains("Shackled Boots"))     return "Shackled Boots";
        if (name.contains("Trapper Boots"))      return "Trapper Boots";
        if (name.contains("Ambush Boots"))       return "Ambush Boots";
        if (name.contains("Carnal Boots"))       return "Carnal Boots";
        if (name.contains("Assassin's Boots"))   return "Assassin's Boots";
        if (name.contains("Murder Boots"))       return "Murder Boots";
        if (name.contains("Wool Shoes"))         return "Wool Shoes";
        if (name.contains("Velvet Slippers"))    return "Velvet Slippers";
        if (name.contains("Silk Slippers"))      return "Silk Slippers";
        if (name.contains("Scholar Boots"))      return "Scholar Boots";
        if (name.contains("Satin Slippers"))     return "Satin Slippers";
        if (name.contains("Samite Slippers"))    return "Samite Slippers";
        if (name.contains("Conjurer Boots"))     return "Conjurer Boots";
        if (name.contains("Arcanist Slippers"))  return "Arcanist Slippers";
        if (name.contains("Sorcerer Boots"))     return "Sorcerer Boots";
        if (name.contains("Iron Greaves"))       return "Iron Greaves";
        if (name.contains("Steel Greaves"))      return "Steel Greaves";
        if (name.contains("Plated Greaves"))     return "Plated Greaves";
        if (name.contains("Reinforced Greaves")) return "Reinforced Greaves";
        if (name.contains("Antique Greaves"))    return "Antique Greaves";
        if (name.contains("Ancient Greaves"))    return "Ancient Greaves";
        if (name.contains("Goliath Greaves"))    return "Goliath Greaves";
        if (name.contains("Vaal Greaves"))       return "Vaal Greaves";
        if (name.contains("Titan Greaves"))      return "Titan Greaves";
        if (name.contains("Leatherscale Boots")) return "Leatherscale Boots";
        if (name.contains("Ironscale Boots"))    return "Ironscale Boots";
        if (name.contains("Bronzescale Boots"))  return "Bronzescale Boots";
        if (name.contains("Steelscale Boots"))   return "Steelscale Boots";
        if (name.contains("Serpentscale Boots")) return "Serpentscale Boots";
        if (name.contains("Wyrmscale Boots"))    return "Wyrmscale Boots";
        if (name.contains("Hydrascale Boots"))   return "Hydrascale Boots";
        if (name.contains("Dragonscale Boots"))  return "Dragonscale Boots";
        if (name.contains("Chain Boots"))        return "Chain Boots";
        if (name.contains("Ringmail Boots"))     return "Ringmail Boots";
        if (name.contains("Mesh Boots"))         return "Mesh Boots";
        if (name.contains("Riveted Boots"))      return "Riveted Boots";
        if (name.contains("Zealot Boots"))       return "Zealot Boots";
        if (name.contains("Soldier Boots"))      return "Soldier Boots";
        if (name.contains("Legion Boots"))       return "Legion Boots";
        if (name.contains("Crusader Boots"))     return "Crusader Boots";
        if (name.contains("Kaom's Greaves"))     return "Kaom's Greaves";
        return null;
    }

    private static String extractGlovesBase(String name) {
        if (name.contains("Gripped Gloves"))         return "Gripped Gloves";
        if (name.contains("Fingerless Silk Gloves")) return "Fingerless Silk Gloves";
        if (name.contains("Spiked Gloves"))          return "Spiked Gloves";
        if (name.contains("Golden Bracers"))         return "Golden Bracers";
        if (name.contains("Rawhide Gloves"))         return "Rawhide Gloves";
        if (name.contains("Goathide Gloves"))        return "Goathide Gloves";
        if (name.contains("Deerskin Gloves"))        return "Deerskin Gloves";
        if (name.contains("Nubuck Gloves"))          return "Nubuck Gloves";
        if (name.contains("Eelskin Gloves"))         return "Eelskin Gloves";
        if (name.contains("Sharkskin Gloves"))       return "Sharkskin Gloves";
        if (name.contains("Shagreen Gloves"))        return "Shagreen Gloves";
        if (name.contains("Stealth Gloves"))         return "Stealth Gloves";
        if (name.contains("Slink Gloves"))           return "Slink Gloves";
        if (name.contains("Wrapped Mitts"))          return "Wrapped Mitts";
        if (name.contains("Strapped Mitts"))         return "Strapped Mitts";
        if (name.contains("Clasped Mitts"))          return "Clasped Mitts";
        if (name.contains("Trapper Mitts"))          return "Trapper Mitts";
        if (name.contains("Ambush Mitts"))           return "Ambush Mitts";
        if (name.contains("Carnal Mitts"))           return "Carnal Mitts";
        if (name.contains("Assassin's Mitts"))       return "Assassin's Mitts";
        if (name.contains("Murder Mitts"))           return "Murder Mitts";
        if (name.contains("Wool Gloves"))            return "Wool Gloves";
        if (name.contains("Velvet Gloves"))          return "Velvet Gloves";
        if (name.contains("Silk Gloves"))            return "Silk Gloves";
        if (name.contains("Embroidered Gloves"))     return "Embroidered Gloves";
        if (name.contains("Satin Gloves"))           return "Satin Gloves";
        if (name.contains("Samite Gloves"))          return "Samite Gloves";
        if (name.contains("Conjurer Gloves"))        return "Conjurer Gloves";
        if (name.contains("Arcanist Gloves"))        return "Arcanist Gloves";
        if (name.contains("Sorcerer Gloves"))        return "Sorcerer Gloves";
        if (name.contains("Iron Gauntlets"))         return "Iron Gauntlets";
        if (name.contains("Plated Gauntlets"))       return "Plated Gauntlets";
        if (name.contains("Bronze Gauntlets"))       return "Bronze Gauntlets";
        if (name.contains("Steel Gauntlets"))        return "Steel Gauntlets";
        if (name.contains("Antique Gauntlets"))      return "Antique Gauntlets";
        if (name.contains("Ancient Gauntlets"))      return "Ancient Gauntlets";
        if (name.contains("Goliath Gauntlets"))      return "Goliath Gauntlets";
        if (name.contains("Vaal Gauntlets"))         return "Vaal Gauntlets";
        if (name.contains("Titan Gauntlets"))        return "Titan Gauntlets";
        if (name.contains("Fishscale Gauntlets"))    return "Fishscale Gauntlets";
        if (name.contains("Ironscale Gauntlets"))    return "Ironscale Gauntlets";
        if (name.contains("Bronzescale Gauntlets"))  return "Bronzescale Gauntlets";
        if (name.contains("Steelscale Gauntlets"))   return "Steelscale Gauntlets";
        if (name.contains("Serpentscale Gauntlets")) return "Serpentscale Gauntlets";
        if (name.contains("Wyrmscale Gauntlets"))    return "Wyrmscale Gauntlets";
        if (name.contains("Hydrascale Gauntlets"))   return "Hydrascale Gauntlets";
        if (name.contains("Dragonscale Gauntlets"))  return "Dragonscale Gauntlets";
        if (name.contains("Chain Gloves"))           return "Chain Gloves";
        if (name.contains("Ringmail Gloves"))        return "Ringmail Gloves";
        if (name.contains("Mesh Gloves"))            return "Mesh Gloves";
        if (name.contains("Riveted Gloves"))         return "Riveted Gloves";
        if (name.contains("Zealot Gloves"))          return "Zealot Gloves";
        if (name.contains("Soldier Gloves"))         return "Soldier Gloves";
        if (name.contains("Legion Gloves"))          return "Legion Gloves";
        if (name.contains("Crusader Gloves"))        return "Crusader Gloves";
        return null;
    }

    private static String extractHelmetBase(String name) {
        if (name.contains("Bone Helmet"))         return "Bone Helmet";
        if (name.contains("Leather Cap"))         return "Leather Cap";
        if (name.contains("Lion Pelt"))           return "Lion Pelt";
        if (name.contains("Tricorne"))            return "Tricorne";
        if (name.contains("Leather Hood"))        return "Leather Hood";
        if (name.contains("Wolf Pelt"))           return "Wolf Pelt";
        if (name.contains("Hunter Hood"))         return "Hunter Hood";
        if (name.contains("Noble Tricorne"))      return "Noble Tricorne";
        if (name.contains("Ursine Pelt"))         return "Ursine Pelt";
        if (name.contains("Silken Hood"))         return "Silken Hood";
        if (name.contains("Sinner Tricorne"))     return "Sinner Tricorne";
        if (name.contains("Scare Mask"))          return "Scare Mask";
        if (name.contains("Vaal Mask"))           return "Vaal Mask";
        if (name.contains("Deicide Mask"))        return "Deicide Mask";
        if (name.contains("Plague Mask"))         return "Plague Mask";
        if (name.contains("Iron Mask"))           return "Iron Mask";
        if (name.contains("Festival Mask"))       return "Festival Mask";
        if (name.contains("Golden Mask"))         return "Golden Mask";
        if (name.contains("Raven Mask"))          return "Raven Mask";
        if (name.contains("Callous Mask"))        return "Callous Mask";
        if (name.contains("Regicide Mask"))       return "Regicide Mask";
        if (name.contains("Harlequin Mask"))      return "Harlequin Mask";
        if (name.contains("Vine Circlet"))        return "Vine Circlet";
        if (name.contains("Mind Cage"))           return "Mind Cage";
        if (name.contains("Hubris Circlet"))      return "Hubris Circlet";
        if (name.contains("Iron Circlet"))        return "Iron Circlet";
        if (name.contains("Torture Cage"))        return "Torture Cage";
        if (name.contains("Tribal Circlet"))      return "Tribal Circlet";
        if (name.contains("Bone Circlet"))        return "Bone Circlet";
        if (name.contains("Lunaris Circlet"))     return "Lunaris Circlet";
        if (name.contains("Steel Circlet"))       return "Steel Circlet";
        if (name.contains("Necromancer Circlet")) return "Necromancer Circlet";
        if (name.contains("Solaris Circlet"))     return "Solaris Circlet";
        if (name.contains("Iron Hat"))            return "Iron Hat";
        if (name.contains("Royal Burgonet"))      return "Royal Burgonet";
        if (name.contains("Eternal Burgonet"))    return "Eternal Burgonet";
        if (name.contains("Cone Helmet"))         return "Cone Helmet";
        if (name.contains("Barbute Helmet"))      return "Barbute Helmet";
        if (name.contains("Close Helmet"))        return "Close Helmet";
        if (name.contains("Gladiator Helmet"))    return "Gladiator Helmet";
        if (name.contains("Reaver Helmet"))       return "Reaver Helmet";
        if (name.contains("Siege Helmet"))        return "Siege Helmet";
        if (name.contains("Samite Helmet"))       return "Samite Helmet";
        if (name.contains("Ezomyte Burgonet"))    return "Ezomyte Burgonet";
        if (name.contains("Battered Helm"))       return "Battered Helm";
        if (name.contains("Nightmare Bascinet"))  return "Nightmare Bascinet";
        if (name.contains("Sallet"))              return "Sallet";
        if (name.contains("Visored Sallet"))      return "Visored Sallet";
        if (name.contains("Gilded Sallet"))       return "Gilded Sallet";
        if (name.contains("Secutor Helm"))        return "Secutor Helm";
        if (name.contains("Fencer Helm"))         return "Fencer Helm";
        if (name.contains("Lacquered Helmet"))    return "Lacquered Helmet";
        if (name.contains("Fluted Bascinet"))     return "Fluted Bascinet";
        if (name.contains("Pig-Faced Bascinet"))  return "Pig-Faced Bascinet";
        if (name.contains("Rusted Coif"))         return "Rusted Coif";
        if (name.contains("Praetor Crown"))       return "Praetor Crown";
        if (name.contains("Soldier Helmet"))      return "Soldier Helmet";
        if (name.contains("Great Helmet"))        return "Great Helmet";
        if (name.contains("Crusader Helmet"))     return "Crusader Helmet";
        if (name.contains("Aventail Helmet"))     return "Aventail Helmet";
        if (name.contains("Zealot Helmet"))       return "Zealot Helmet";
        if (name.contains("Great Crown"))         return "Great Crown";
        if (name.contains("Magistrate Crown"))    return "Magistrate Crown";
        if (name.contains("Prophet Crown"))       return "Prophet Crown";
        if (name.contains("Golden Wreath"))       return "Golden Wreath";
        return null;
    }

    private static String extractShieldBase(String name) {
        if (name.contains("Golden Flame"))             return "Golden Flame";
        if (name.contains("Goathide Buckler"))         return "Goathide Buckler";
        if (name.contains("Battle Buckler"))           return "Battle Buckler";
        if (name.contains("Golden Buckler"))           return "Golden Buckler";
        if (name.contains("Ironwood Buckler"))         return "Ironwood Buckler";
        if (name.contains("Lacquered Buckler"))        return "Lacquered Buckler";
        if (name.contains("Vaal Buckler"))             return "Vaal Buckler";
        if (name.contains("Crusader Buckler"))         return "Crusader Buckler";
        if (name.contains("Imperial Buckler"))         return "Imperial Buckler";
        if (name.contains("Pine Buckler"))             return "Pine Buckler";
        if (name.contains("Painted Buckler"))          return "Painted Buckler";
        if (name.contains("Hammered Buckler"))         return "Hammered Buckler";
        if (name.contains("War Buckler"))              return "War Buckler";
        if (name.contains("Gilded Buckler"))           return "Gilded Buckler";
        if (name.contains("Oak Buckler"))              return "Oak Buckler";
        if (name.contains("Enameled Buckler"))         return "Enameled Buckler";
        if (name.contains("Corrugated Buckler"))       return "Corrugated Buckler";
        if (name.contains("Spiked Bundle"))            return "Spiked Bundle";
        if (name.contains("Alder Spiked Shield"))      return "Alder Spiked Shield";
        if (name.contains("Ezomyte Spiked Shield"))    return "Ezomyte Spiked Shield";
        if (name.contains("Mirrored Spiked Shield"))   return "Mirrored Spiked Shield";
        if (name.contains("Supreme Spiked Shield"))    return "Supreme Spiked Shield";
        if (name.contains("Driftwood Spiked Shield"))  return "Driftwood Spiked Shield";
        if (name.contains("Alloyed Spiked Shield"))    return "Alloyed Spiked Shield";
        if (name.contains("Burnished Spiked Shield"))  return "Burnished Spiked Shield";
        if (name.contains("Ornate Spiked Shield"))     return "Ornate Spiked Shield";
        if (name.contains("Redwood Spiked Shield"))    return "Redwood Spiked Shield";
        if (name.contains("Compound Spiked Shield"))   return "Compound Spiked Shield";
        if (name.contains("Polished Spiked Shield"))   return "Polished Spiked Shield";
        if (name.contains("Sovereign Spiked Shield"))  return "Sovereign Spiked Shield";
        if (name.contains("Twig Spirit Shield"))       return "Twig Spirit Shield";
        if (name.contains("Chiming Spirit Shield"))    return "Chiming Spirit Shield";
        if (name.contains("Thorium Spirit Shield"))    return "Thorium Spirit Shield";
        if (name.contains("Lacewood Spirit Shield"))   return "Lacewood Spirit Shield";
        if (name.contains("Fossilised Spirit Shield")) return "Fossilised Spirit Shield";
        if (name.contains("Vaal Spirit Shield"))       return "Vaal Spirit Shield";
        if (name.contains("Harmonic Spirit Shield"))   return "Harmonic Spirit Shield";
        if (name.contains("Titanium Spirit Shield"))   return "Titanium Spirit Shield";
        if (name.contains("Yew Spirit Shield"))        return "Yew Spirit Shield";
        if (name.contains("Bone Spirit Shield"))       return "Bone Spirit Shield";
        if (name.contains("Tarnished Spirit Shield"))  return "Tarnished Spirit Shield";
        if (name.contains("Jingling Spirit Shield"))   return "Jingling Spirit Shield";
        if (name.contains("Brass Spirit Shield"))      return "Brass Spirit Shield";
        if (name.contains("Walnut Spirit Shield"))     return "Walnut Spirit Shield";
        if (name.contains("Ivory Spirit Shield"))      return "Ivory Spirit Shield";
        if (name.contains("Ancient Spirit Shield"))    return "Ancient Spirit Shield";
        if (name.contains("Splintered Tower Shield"))  return "Splintered Tower Shield";
        if (name.contains("Bronze Tower Shield"))      return "Bronze Tower Shield";
        if (name.contains("Girded Tower Shield"))      return "Girded Tower Shield";
        if (name.contains("Crested Tower Shield"))     return "Crested Tower Shield";
        if (name.contains("Shagreen Tower Shield"))    return "Shagreen Tower Shield";
        if (name.contains("Ebony Tower Shield"))       return "Ebony Tower Shield";
        if (name.contains("Ezomyte Tower Shield"))     return "Ezomyte Tower Shield";
        if (name.contains("Colossal Tower Shield"))    return "Colossal Tower Shield";
        if (name.contains("Pinnacle Tower Shield"))    return "Pinnacle Tower Shield";
        if (name.contains("Corroded Tower Shield"))    return "Corroded Tower Shield";
        if (name.contains("Rawhide Tower Shield"))     return "Rawhide Tower Shield";
        if (name.contains("Cedar Tower Shield"))       return "Cedar Tower Shield";
        if (name.contains("Copper Tower Shield"))      return "Copper Tower Shield";
        if (name.contains("Reinforced Tower Shield"))  return "Reinforced Tower Shield";
        if (name.contains("Painted Tower Shield"))     return "Painted Tower Shield";
        if (name.contains("Buckskin Tower Shield"))    return "Buckskin Tower Shield";
        if (name.contains("Mahogany Tower Shield"))    return "Mahogany Tower Shield";
        if (name.contains("Rotted Round Shield"))      return "Rotted Round Shield";
        if (name.contains("Teak Round Shield"))        return "Teak Round Shield";
        if (name.contains("Spiny Round Shield"))       return "Spiny Round Shield";
        if (name.contains("Cardinal Round Shield"))    return "Cardinal Round Shield";
        if (name.contains("Elegant Round Shield"))     return "Elegant Round Shield";
        if (name.contains("Fir Round Shield"))         return "Fir Round Shield";
        if (name.contains("Studded Round Shield"))     return "Studded Round Shield";
        if (name.contains("Scarlet Round Shield"))     return "Scarlet Round Shield";
        if (name.contains("Splendid Round Shield"))    return "Splendid Round Shield";
        if (name.contains("Maple Round Shield"))       return "Maple Round Shield";
        if (name.contains("Spiked Round Shield"))      return "Spiked Round Shield";
        if (name.contains("Crimson Round Shield"))     return "Crimson Round Shield";
        if (name.contains("Baroque Round Shield"))     return "Baroque Round Shield";
        if (name.contains("Plank Kite Shield"))        return "Plank Kite Shield";
        if (name.contains("Branded Kite Shield"))      return "Branded Kite Shield";
        if (name.contains("Champion Kite Shield"))     return "Champion Kite Shield";
        if (name.contains("Mosaic Kite Shield"))       return "Mosaic Kite Shield";
        if (name.contains("Archon Kite Shield"))       return "Archon Kite Shield";
        if (name.contains("Linden Kite Shield"))       return "Linden Kite Shield";
        if (name.contains("Reinforced Kite Shield"))   return "Reinforced Kite Shield";
        if (name.contains("Layered Kite Shield"))      return "Layered Kite Shield";
        if (name.contains("Ceremonial Kite Shield"))   return "Ceremonial Kite Shield";
        if (name.contains("Etched Kite Shield"))       return "Etched Kite Shield";
        if (name.contains("Steel Kite Shield"))        return "Steel Kite Shield";
        if (name.contains("Laminated Kite Shield"))    return "Laminated Kite Shield";
        if (name.contains("Angelic Kite Shield"))      return "Angelic Kite Shield";
        return null;
    }

    private static String extractBeltBase(String name) {
        if (name.contains("Rustic Sash"))   return "Rustic Sash";
        if (name.contains("Chain Belt"))    return "Chain Belt";
        if (name.contains("Leather Belt"))  return "Leather Belt";
        if (name.contains("Heavy Belt"))    return "Heavy Belt";
        if (name.contains("Cloth Belt"))    return "Cloth Belt";
        if (name.contains("Studded Belt"))  return "Studded Belt";
        if (name.contains("Stygian Vise"))  return "Stygian Vise";
        if (name.contains("Vanguard Belt")) return "Vanguard Belt";
        if (name.contains("Crystal Belt"))  return "Crystal Belt";
        if (name.contains("Golden Obi"))    return "Golden Obi";
        return null;
    }

    private static String extractJewelBase(String name) {
        if (name.contains("Hypnotic Eye Jewel"))  return "Hypnotic Eye Jewel";
        if (name.contains("Murderous Eye Jewel")) return "Murderous Eye Jewel";
        if (name.contains("Searching Eye Jewel")) return "Searching Eye Jewel";
        if (name.contains("Ghastly Eye Jewel"))   return "Ghastly Eye Jewel";
        if (name.contains("Viridian Jewel"))      return "Viridian Jewel";
        if (name.contains("Cobalt Jewel"))        return "Cobalt Jewel";
        if (name.contains("Prismatic Jewel"))     return "Prismatic Jewel";
        if (name.contains("Crimson Jewel"))       return "Crimson Jewel";
        return null;
    }

    private static String extractQuiverBase(String name) {
        if (name.contains("Cured Quiver"))             return "Cured Quiver";
        if (name.contains("Fire Arrow Quiver"))        return "Fire Arrow Quiver";
        if (name.contains("Broadhead Arrow Quiver"))   return "Broadhead Arrow Quiver";
        if (name.contains("Penetrating Arrow Quiver")) return "Penetrating Arrow Quiver";
        if (name.contains("Spike-Point Arrow Quiver")) return "Spike-Point Arrow Quiver";
        if (name.contains("Rugged Quiver"))            return "Rugged Quiver";
        if (name.contains("Conductive Quiver"))        return "Conductive Quiver";
        if (name.contains("Heavy Quiver"))             return "Heavy Quiver";
        if (name.contains("Light Quiver"))             return "Light Quiver";
        if (name.contains("Serrated Arrow Quiver"))    return "Serrated Arrow Quiver";
        if (name.contains("Two-Point Arrow Quiver"))   return "Two-Point Arrow Quiver";
        if (name.contains("Sharktooth Arrow Quiver"))  return "Sharktooth Arrow Quiver";
        if (name.contains("Blunt Arrow Quiver"))       return "Blunt Arrow Quiver";
        return null;
    }

    private static String extractRingBase(String name) {
        if (name.contains("Breach Ring"))    return "Breach Ring";
        if (name.contains("Iron Ring"))      return "Iron Ring";
        if (name.contains("Amethyst Ring"))  return "Amethyst Ring";
        if (name.contains("Diamond Ring"))   return "Diamond Ring";
        if (name.contains("Two-Stone Ring")) return "Two-Stone Ring";
        if (name.contains("Unset Ring"))     return "Unset Ring";
        if (name.contains("Coral Ring"))     return "Coral Ring";
        if (name.contains("Paua Ring"))      return "Paua Ring";
        if (name.contains("Gold Ring"))      return "Gold Ring";
        if (name.contains("Topaz Ring"))     return "Topaz Ring";
        if (name.contains("Sapphire Ring"))  return "Sapphire Ring";
        if (name.contains("Ruby Ring"))      return "Ruby Ring";
        if (name.contains("Prismatic Ring")) return "Prismatic Ring";
        if (name.contains("Moonstone Ring")) return "Moonstone Ring";
        if (name.contains("Steel Ring"))     return "Steel Ring";
        if (name.contains("Opal Ring"))      return "Opal Ring";
        if (name.contains("Golden Hoop"))    return "Golden Hoop";
        if (name.contains("Jet Ring"))       return "Jet Ring";
        return null;
    }

    private static String extractClawBase(String name) {
        if (name.contains("Nailed Fist"))      return "Nailed Fist";
        if (name.contains("Gouger"))           return "Gouger";
        if (name.contains("Tiger's Paw"))      return "Tiger's Paw";
        if (name.contains("Gut Ripper"))       return "Gut Ripper";
        if (name.contains("Prehistoric Claw")) return "Prehistoric Claw";
        if (name.contains("Noble Claw"))       return "Noble Claw";
        if (name.contains("Eagle Claw"))       return "Eagle Claw";
        if (name.contains("Great White Claw")) return "Great White Claw";
        if (name.contains("Throat Stabber"))   return "Throat Stabber";
        if (name.contains("Hellion's Paw"))    return "Hellion's Paw";
        if (name.contains("Eye Gouger"))       return "Eye Gouger";
        if (name.contains("Sharktooth Claw"))  return "Sharktooth Claw";
        if (name.contains("Vaal Claw"))        return "Vaal Claw";
        if (name.contains("Imperial Claw"))    return "Imperial Claw";
        if (name.contains("Terror Claw"))      return "Terror Claw";
        if (name.contains("Awl"))              return "Awl";
        if (name.contains("Cat's Paw"))        return "Cat's Paw";
        if (name.contains("Blinder"))          return "Blinder";
        if (name.contains("Timeworn Claw"))    return "Timeworn Claw";
        if (name.contains("Sparkling Claw"))   return "Sparkling Claw";
        if (name.contains("Fright Claw"))      return "Fright Claw";
        if (name.contains("Thresher Claw"))    return "Thresher Claw";
        if (name.contains("Double Claw"))      return "Double Claw";
        if (name.contains("Twin Claw"))        return "Twin Claw";
        if (name.contains("Gemini Claw"))      return "Gemini Claw";
        return null;
    }

    private static String extractDaggerBase(String name) {
        if (name.contains("Glass Shank"))     return "Glass Shank";
        if (name.contains("Butcher Knife"))   return "Butcher Knife";
        if (name.contains("Poignard"))        return "Poignard";
        if (name.contains("Boot Blade"))      return "Boot Blade";
        if (name.contains("Golden Kris"))     return "Golden Kris";
        if (name.contains("Royal Skean"))     return "Royal Skean";
        if (name.contains("Fiend Dagger"))    return "Fiend Dagger";
        if (name.contains("Gutting Knife"))   return "Gutting Knife";
        if (name.contains("Slaughter Knife")) return "Slaughter Knife";
        if (name.contains("Ambusher"))        return "Ambusher";
        if (name.contains("Ezomyte Dagger"))  return "Ezomyte Dagger";
        if (name.contains("Skinning Knife"))  return "Skinning Knife";
        if (name.contains("Platinum Kris"))   return "Platinum Kris";
        if (name.contains("Imperial Skean"))  return "Imperial Skean";
        if (name.contains("Demon Dagger"))    return "Demon Dagger";
        if (name.contains("Carving Knife"))   return "Carving Knife";
        if (name.contains("Stiletto"))        return "Stiletto";
        if (name.contains("Boot Knife"))      return "Boot Knife";
        if (name.contains("Copper Kris"))     return "Copper Kris";
        if (name.contains("Skean"))           return "Skean";
        if (name.contains("Imp Dagger"))      return "Imp Dagger";
        if (name.contains("Flaying Knife"))   return "Flaying Knife";
        if (name.contains("Prong Dagger"))    return "Prong Dagger";
        if (name.contains("Trisula"))         return "Trisula";
        if (name.contains("Sai"))             return "Sai";
        return null;
    }

    private static String extractOneaxeBase(String name) {
        if (name.contains("Rusted Hatchet"))   return "Rusted Hatchet";
        if (name.contains("Tomahawk"))         return "Tomahawk";
        if (name.contains("Wrist Chopper"))    return "Wrist Chopper";
        if (name.contains("War Axe"))          return "War Axe";
        if (name.contains("Chest Splitter"))   return "Chest Splitter";
        if (name.contains("Ceremonial Axe"))   return "Ceremonial Axe";
        if (name.contains("Wraith Axe"))       return "Wraith Axe";
        if (name.contains("Karui Axe"))        return "Karui Axe";
        if (name.contains("Siege Axe"))        return "Siege Axe";
        if (name.contains("Reaver Axe"))       return "Reaver Axe";
        if (name.contains("Butcher Axe"))      return "Butcher Axe";
        if (name.contains("Jade Hatchet"))     return "Jade Hatchet";
        if (name.contains("Vaal Hatchet"))     return "Vaal Hatchet";
        if (name.contains("Royal Axe"))        return "Royal Axe";
        if (name.contains("Infernal Axe"))     return "Infernal Axe";
        if (name.contains("Boarding Axe"))     return "Boarding Axe";
        if (name.contains("Cleaver"))          return "Cleaver";
        if (name.contains("Broad Axe"))        return "Broad Axe";
        if (name.contains("Arming Axe"))       return "Arming Axe";
        if (name.contains("Decorative Axe"))   return "Decorative Axe";
        if (name.contains("Spectral Axe"))     return "Spectral Axe";
        if (name.contains("Jasper Axe"))       return "Jasper Axe";
        if (name.contains("Etched Hatchet"))   return "Etched Hatchet";
        if (name.contains("Engraved Hatchet")) return "Engraved Hatchet";
        if (name.contains("Runic Hatchet"))    return "Runic Hatchet";
        return null;
    }

    private static String extractOnemaceBase(String name) {
        if (name.contains("Driftwood Club"))  return "Driftwood Club";
        if (name.contains("Barbed Club"))     return "Barbed Club";
        if (name.contains("Rock Breaker"))    return "Rock Breaker";
        if (name.contains("Battle Hammer"))   return "Battle Hammer";
        if (name.contains("Flanged Mace"))    return "Flanged Mace";
        if (name.contains("Ornate Mace"))     return "Ornate Mace";
        if (name.contains("Phantom Mace"))    return "Phantom Mace";
        if (name.contains("Ancestral Club"))  return "Ancestral Club";
        if (name.contains("Tenderizer"))      return "Tenderizer";
        if (name.contains("Gavel"))           return "Gavel";
        if (name.contains("Legion Hammer"))   return "Legion Hammer";
        if (name.contains("Tribal Club"))     return "Tribal Club";
        if (name.contains("Pernarch"))        return "Pernarch";
        if (name.contains("Auric Mace"))      return "Auric Mace";
        if (name.contains("Nightmare Mace"))  return "Nightmare Mace";
        if (name.contains("Spiked Club"))     return "Spiked Club";
        if (name.contains("Stone Hammer"))    return "Stone Hammer";
        if (name.contains("War Hammer"))      return "War Hammer";
        if (name.contains("Bladed Mace"))     return "Bladed Mace";
        if (name.contains("Ceremonial Mace")) return "Ceremonial Mace";
        if (name.contains("Dream Mace"))      return "Dream Mace";
        if (name.contains("Petrified Club"))  return "Petrified Club";
        if (name.contains("Wyrm Mace"))       return "Wyrm Mace";
        if (name.contains("Dragon Mace"))     return "Dragon Mace";
        if (name.contains("Behemoth Mace"))   return "Behemoth Mace";
        return null;
    }

    private static String extractSceptreBase(String name) {
        if (name.contains("Driftwood Sceptre")) return "Driftwood Sceptre";
        if (name.contains("Sekhem"))            return "Sekhem";
        if (name.contains("Crystal Sceptre"))   return "Crystal Sceptre";
        if (name.contains("Lead Sceptre"))      return "Lead Sceptre";
        if (name.contains("Blood Sceptre"))     return "Blood Sceptre";
        if (name.contains("Royal Sceptre"))     return "Royal Sceptre";
        if (name.contains("Abyssal Sceptre"))   return "Abyssal Sceptre";
        if (name.contains("Karui Sceptre"))     return "Karui Sceptre";
        if (name.contains("Tyrant's Sekhem"))   return "Tyrant's Sekhem";
        if (name.contains("Opal Sceptre"))      return "Opal Sceptre";
        if (name.contains("Platinum Sceptre"))  return "Platinum Sceptre";
        if (name.contains("Darkwood Sceptre"))  return "Darkwood Sceptre";
        if (name.contains("Vaal Sceptre"))      return "Vaal Sceptre";
        if (name.contains("Carnal Sceptre"))    return "Carnal Sceptre";
        if (name.contains("Void Sceptre"))      return "Void Sceptre";
        if (name.contains("Bronze Sceptre"))    return "Bronze Sceptre";
        if (name.contains("Quartz Sceptre"))    return "Quartz Sceptre";
        if (name.contains("Iron Sceptre"))      return "Iron Sceptre";
        if (name.contains("Ochre Sceptre"))     return "Ochre Sceptre";
        if (name.contains("Ritual Sceptre"))    return "Ritual Sceptre";
        if (name.contains("Shadow Sceptre"))    return "Shadow Sceptre";
        if (name.contains("Grinning Fetish"))   return "Grinning Fetish";
        if (name.contains("Horned Sceptre"))    return "Horned Sceptre";
        if (name.contains("Stag Sceptre"))      return "Stag Sceptre";
        if (name.contains("Sambar Sceptre"))    return "Sambar Sceptre";
        return null;
    }

    private static String extractOneswordBase(String name) {
        if (name.contains("Rusted Sword"))      return "Rusted Sword";
        if (name.contains("Cutlass"))           return "Cutlass";
        if (name.contains("Baselard"))          return "Baselard";
        if (name.contains("Battle Sword"))      return "Battle Sword";
        if (name.contains("Elder Sword"))       return "Elder Sword";
        if (name.contains("Graceful Sword"))    return "Graceful Sword";
        if (name.contains("Twilight Blade"))    return "Twilight Blade";
        if (name.contains("Gemstone Sword"))    return "Gemstone Sword";
        if (name.contains("Corsair Sword"))     return "Corsair Sword";
        if (name.contains("Gladius"))           return "Gladius";
        if (name.contains("Legion Sword"))      return "Legion Sword";
        if (name.contains("Copper Sword"))      return "Copper Sword";
        if (name.contains("Vaal Blade"))        return "Vaal Blade";
        if (name.contains("Eternal Sword"))     return "Eternal Sword";
        if (name.contains("Midnight Blade"))    return "Midnight Blade";
        if (name.contains("Sabre"))             return "Sabre";
        if (name.contains("Broad Sword"))       return "Broad Sword";
        if (name.contains("War Sword"))         return "War Sword";
        if (name.contains("Ancient Sword"))     return "Ancient Sword";
        if (name.contains("Elegant Sword"))     return "Elegant Sword";
        if (name.contains("Dusk Blade"))        return "Dusk Blade";
        if (name.contains("Variscite Blade"))   return "Variscite Blade";
        if (name.contains("Hook Sword"))        return "Hook Sword";
        if (name.contains("Grappler"))          return "Grappler";
        if (name.contains("Tiger Hook"))        return "Tiger Hook";
        if (name.contains("Rusted Spike"))      return "Rusted Spike";
        if (name.contains("Burnished Foil"))    return "Burnished Foil";
        if (name.contains("Estoc"))             return "Estoc";
        if (name.contains("Serrated Foil"))     return "Serrated Foil";
        if (name.contains("Primeval Rapier"))   return "Primeval Rapier";
        if (name.contains("Fancy Foil"))        return "Fancy Foil";
        if (name.contains("Apex Rapier"))       return "Apex Rapier";
        if (name.contains("Dragonbone Rapier")) return "Dragonbone Rapier";
        if (name.contains("Tempered Foil"))     return "Tempered Foil";
        if (name.contains("Pecoraro"))          return "Pecoraro";
        if (name.contains("Spiraled Foil"))     return "Spiraled Foil";
        if (name.contains("Whalebone Rapier"))  return "Whalebone Rapier";
        if (name.contains("Vaal Rapier"))       return "Vaal Rapier";
        if (name.contains("Jewelled Foil"))     return "Jewelled Foil";
        if (name.contains("Harpy Rapier"))      return "Harpy Rapier";
        if (name.contains("Battered Foil"))     return "Battered Foil";
        if (name.contains("Basket Rapier"))     return "Basket Rapier";
        if (name.contains("Jagged Foil"))       return "Jagged Foil";
        if (name.contains("Antique Rapier"))    return "Antique Rapier";
        if (name.contains("Elegant Foil"))      return "Elegant Foil";
        if (name.contains("Thorn Rapier"))      return "Thorn Rapier";
        if (name.contains("Wyrmbone Rapier"))   return "Wyrmbone Rapier";
        if (name.contains("Smallsword"))        return "Smallsword";
        if (name.contains("Courtesan Sword"))   return "Courtesan Sword";
        if (name.contains("Dragoon Sword"))     return "Dragoon Sword";
        if (name.contains("Charan's Sword"))    return "Charan's Sword";
        return null;
    }

    private static String extractWandBase(String name) {
        if (name.contains("Driftwood Wand")) return "Driftwood Wand";
        if (name.contains("Serpent Wand"))   return "Serpent Wand";
        if (name.contains("Omen Wand"))      return "Omen Wand";
        if (name.contains("Demon's Horn"))   return "Demon's Horn";
        if (name.contains("Imbued Wand"))    return "Imbued Wand";
        if (name.contains("Opal Wand"))      return "Opal Wand";
        if (name.contains("Tornado Wand"))   return "Tornado Wand";
        if (name.contains("Prophecy Wand"))  return "Prophecy Wand";
        if (name.contains("Goat's Horn"))    return "Goat's Horn";
        if (name.contains("Carved Wand"))    return "Carved Wand";
        if (name.contains("Quartz Wand"))    return "Quartz Wand";
        if (name.contains("Spiraled Wand"))  return "Spiraled Wand";
        if (name.contains("Sage Wand"))      return "Sage Wand";
        if (name.contains("Faun's Horn"))    return "Faun's Horn";
        if (name.contains("Engraved Wand"))  return "Engraved Wand";
        if (name.contains("Crystal Wand"))   return "Crystal Wand";
        if (name.contains("Pagan Wand"))     return "Pagan Wand";
        if (name.contains("Heathen Wand"))   return "Heathen Wand";
        if (name.contains("Profane Wand"))   return "Profane Wand";
        return null;
    }

    private static String extractRodBase(String name) {
        if (name.contains("Fishing Rod")) return "Fishing Rod";
        return null;
    }

    private static String extractBowBase(String name) {
        if (name.contains("Crude Bow"))      return "Crude Bow";
        if (name.contains("Decurve Bow"))    return "Decurve Bow";
        if (name.contains("Compound Bow"))   return "Compound Bow";
        if (name.contains("Sniper Bow"))     return "Sniper Bow";
        if (name.contains("Ivory Bow"))      return "Ivory Bow";
        if (name.contains("Highborn Bow"))   return "Highborn Bow";
        if (name.contains("Decimation Bow")) return "Decimation Bow";
        if (name.contains("Thicket Bow"))    return "Thicket Bow";
        if (name.contains("Citadel Bow"))    return "Citadel Bow";
        if (name.contains("Ranger Bow"))     return "Ranger Bow";
        if (name.contains("Assassin Bow"))   return "Assassin Bow";
        if (name.contains("Short Bow"))      return "Short Bow";
        if (name.contains("Spine Bow"))      return "Spine Bow";
        if (name.contains("Imperial Bow"))   return "Imperial Bow";
        if (name.contains("Harbinger Bow"))  return "Harbinger Bow";
        if (name.contains("Long Bow"))       return "Long Bow";
        if (name.contains("Composite Bow"))  return "Composite Bow";
        if (name.contains("Recurve Bow"))    return "Recurve Bow";
        if (name.contains("Bone Bow"))       return "Bone Bow";
        if (name.contains("Royal Bow"))      return "Royal Bow";
        if (name.contains("Death Bow"))      return "Death Bow";
        if (name.contains("Grove Bow"))      return "Grove Bow";
        if (name.contains("Reflex Bow"))     return "Reflex Bow";
        if (name.contains("Steelwood Bow"))  return "Steelwood Bow";
        if (name.contains("Maraketh Bow"))   return "Maraketh Bow";
        return null;
    }

    private static String extractStaffBase(String name) {
        if (name.contains("Gnarled Branch"))   return "Gnarled Branch";
        if (name.contains("Military Staff"))   return "Military Staff";
        if (name.contains("Serpentine Staff")) return "Serpentine Staff";
        if (name.contains("Highborn Staff"))   return "Highborn Staff";
        if (name.contains("Foul Staff"))       return "Foul Staff";
        if (name.contains("Primordial Staff")) return "Primordial Staff";
        if (name.contains("Lathi"))            return "Lathi";
        if (name.contains("Ezomyte Staff"))    return "Ezomyte Staff";
        if (name.contains("Maelström Staff"))  return "Maelström Staff";
        if (name.contains("Imperial Staff"))   return "Imperial Staff";
        if (name.contains("Judgement Staff"))  return "Judgement Staff";
        if (name.contains("Primitive Staff"))  return "Primitive Staff";
        if (name.contains("Long Staff"))       return "Long Staff";
        if (name.contains("Iron Staff"))       return "Iron Staff";
        if (name.contains("Coiled Staff"))     return "Coiled Staff";
        if (name.contains("Royal Staff"))      return "Royal Staff";
        if (name.contains("Vile Staff"))       return "Vile Staff";
        if (name.contains("Woodful Staff"))    return "Woodful Staff";
        if (name.contains("Quarterstaff"))     return "Quarterstaff";
        if (name.contains("Crescent Staff"))   return "Crescent Staff";
        if (name.contains("Moon Staff"))       return "Moon Staff";
        if (name.contains("Eclipse Staff"))    return "Eclipse Staff";
        return null;
    }

    private static String extractTwoaxeBase(String name) {
        if (name.contains("Stone Axe"))      return "Stone Axe";
        if (name.contains("Headsman Axe"))   return "Headsman Axe";
        if (name.contains("Labrys"))         return "Labrys";
        if (name.contains("Noble Axe"))      return "Noble Axe";
        if (name.contains("Abyssal Axe"))    return "Abyssal Axe";
        if (name.contains("Karui Chopper"))  return "Karui Chopper";
        if (name.contains("Sundering Axe"))  return "Sundering Axe";
        if (name.contains("Ezomyte Axe"))    return "Ezomyte Axe";
        if (name.contains("Vaal Axe"))       return "Vaal Axe";
        if (name.contains("Despot Axe"))     return "Despot Axe";
        if (name.contains("Void Axe"))       return "Void Axe";
        if (name.contains("Jade Chopper"))   return "Jade Chopper";
        if (name.contains("Woodsplitter"))   return "Woodsplitter";
        if (name.contains("Poleaxe"))        return "Poleaxe";
        if (name.contains("Double Axe"))     return "Double Axe";
        if (name.contains("Gilded Axe"))     return "Gilded Axe";
        if (name.contains("Shadow Axe"))     return "Shadow Axe";
        if (name.contains("Jasper Chopper")) return "Jasper Chopper";
        if (name.contains("Timber Axe"))     return "Timber Axe";
        if (name.contains("Dagger Axe"))     return "Dagger Axe";
        if (name.contains("Talon Axe"))      return "Talon Axe";
        if (name.contains("Fleshripper"))    return "Fleshripper";
        return null;
    }

    private static String extractTwomaceBase(String name) {
        if (name.contains("Driftwood Maul"))  return "Driftwood Maul";
        if (name.contains("Steelhead"))       return "Steelhead";
        if (name.contains("Spiny Maul"))      return "Spiny Maul";
        if (name.contains("Plated Maul"))     return "Plated Maul";
        if (name.contains("Dread Maul"))      return "Dread Maul";
        if (name.contains("Karui Maul"))      return "Karui Maul";
        if (name.contains("Colossus Mallet")) return "Colossus Mallet";
        if (name.contains("Piledriver"))      return "Piledriver";
        if (name.contains("Meatgrinder"))     return "Meatgrinder";
        if (name.contains("Imperial Maul"))   return "Imperial Maul";
        if (name.contains("Terror Maul"))     return "Terror Maul";
        if (name.contains("Tribal Maul"))     return "Tribal Maul";
        if (name.contains("Mallet"))          return "Mallet";
        if (name.contains("Sledgehammer"))    return "Sledgehammer";
        if (name.contains("Jagged Maul"))     return "Jagged Maul";
        if (name.contains("Brass Maul"))      return "Brass Maul";
        if (name.contains("Fright Maul"))     return "Fright Maul";
        if (name.contains("Totemic Maul"))    return "Totemic Maul";
        if (name.contains("Great Mallet"))    return "Great Mallet";
        if (name.contains("Morning Star"))    return "Morning Star";
        if (name.contains("Solar Maul"))      return "Solar Maul";
        if (name.contains("Coronal Maul"))    return "Coronal Maul";
        return null;
    }

    private static String extractTwoswordBase(String name) {
        if (name.contains("Corroded Blade"))      return "Corroded Blade";
        if (name.contains("Highland Blade"))      return "Highland Blade";
        if (name.contains("Engraved Greatsword")) return "Engraved Greatsword";
        if (name.contains("Tiger Sword"))         return "Tiger Sword";
        if (name.contains("Wraith Sword"))        return "Wraith Sword";
        if (name.contains("Headman's Sword"))     return "Headman's Sword";
        if (name.contains("Reaver Sword"))        return "Reaver Sword";
        if (name.contains("Ezomyte Blade"))       return "Ezomyte Blade";
        if (name.contains("Vaal Greatsword"))     return "Vaal Greatsword";
        if (name.contains("Lion Sword"))          return "Lion Sword";
        if (name.contains("Infernal Sword"))      return "Infernal Sword";
        if (name.contains("Longsword"))           return "Longsword";
        if (name.contains("Bastard Sword"))       return "Bastard Sword";
        if (name.contains("Two-Handed Sword"))    return "Two-Handed Sword";
        if (name.contains("Etched Greatsword"))   return "Etched Greatsword";
        if (name.contains("Ornate Sword"))        return "Ornate Sword";
        if (name.contains("Spectral Sword"))      return "Spectral Sword";
        if (name.contains("Butcher Sword"))       return "Butcher Sword";
        if (name.contains("Footman Sword"))       return "Footman Sword";
        if (name.contains("Keyblade"))            return "Keyblade";
        if (name.contains("Curved Blade"))        return "Curved Blade";
        if (name.contains("Lithe Blade"))         return "Lithe Blade";
        if (name.contains("Exquisite Blade"))     return "Exquisite Blade";
        return null;
    }
}