package poe.Managers.Relation;

public class BaseMaps {
    public static final String[] maps = {
            "Shaped Underground River Map",
            "Elder Defiled Cathedral Map",
            "Elder Primordial Blocks Map",
            "Elder Underground River Map",
            "Shaped Overgrown Shrine Map",
            "Shaped Infested Valley Map",
            "Shaped Burial Chambers Map",
            "Shaped Haunted Mansion Map",
            "Shaped Tropical Island Map",
            "Shaped Primordial Pool Map",
            "Shaped Underground Sea Map",
            "Elder Overgrown Shrine Map",
            "Elder Primordial Pool Map",
            "Shaped Phantasmagoria Map",
            "Elder Tropical Island Map",
            "Shaped Overgrown Ruin Map",
            "Elder Torture Chamber Map",
            "Shaped Relic Chambers Map",
            "Elder Infested Valley Map",
            "Elder Haunted Mansion Map",
            "Elder Underground Sea Map",
            "Elder Burial Chambers Map",
            "Elder Relic Chambers Map",
            "Shaped Sulphur Vents Map",
            "Shaped Arachnid Tomb Map",
            "Shaped Fungal Hollow Map",
            "Maze of the Minotaur Map",
            "Shaped Spider Forest Map",
            "Shaped Desert Spring Map",
            "Shaped Mineral Pools Map",
            "Elder Overgrown Ruin Map",
            "Elder Crimson Temple Map",
            "Forge of the Phoenix Map",
            "Elder Phantasmagoria Map",
            "Shaped Jungle Valley Map",
            "Shaped Arachnid Nest Map",
            "Shaped Ancient City Map",
            "Shaped Conservatory Map",
            "Elder Sulphur Vents Map",
            "Shaped Vaal Pyramid Map",
            "Shaped Flooded Mine Map",
            "Elder Fungal Hollow Map",
            "Shaped Ivory Temple Map",
            "Elder Arachnid Nest Map",
            "Shaped Acid Caverns Map",
            "Shaped Lava Chamber Map",
            "Shaped Castle Ruins Map",
            "Elder Mineral Pools Map",
            "Elder Arachnid Tomb Map",
            "Elder Jungle Valley Map",
            "Elder Desert Spring Map",
            "Shaped Cursed Crypt Map",
            "Elder Spider Forest Map",
            "Shaped Spider Lair Map",
            "Elder Flooded Mine Map",
            "Elder Cursed Crypt Map",
            "Shaped Coral Ruins Map",
            "Elder Castle Ruins Map",
            "Shaped Scriptorium Map",
            "Shaped Crystal Ore Map",
            "Elder Ivory Temple Map",
            "Pit of the Chimera Map",
            "Elder Conservatory Map",
            "Elder Ancient City Map",
            "Shaped City Square Map",
            "Elder Vaal Pyramid Map",
            "Elder Malformation Map",
            "Elder Lava Chamber Map",
            "Shaped Moon Temple Map",
            "Shaped Toxic Sewer Map",
            "Shaped Ashen Wood Map",
            "Underground River Map",
            "Elder Scriptorium Map",
            "Shaped Laboratory Map",
            "Elder Dark Forest Map",
            "Elder City Square Map",
            "Elder Toxic Sewer Map",
            "Elder Moon Temple Map",
            "Shaped Mud Geyser Map",
            "Defiled Cathedral Map",
            "Elder Crystal Ore Map",
            "Shaped Bone Crypt Map",
            "Shaped Waste Pool Map",
            "Elder Coral Ruins Map",
            "Elder Spider Lair Map",
            "Shaped Racecourse Map",
            "Shaped Courthouse Map",
            "Lair of the Hydra Map",
            "Shaped Excavation Map",
            "Elder Sunken City Map",
            "Shaped Lighthouse Map",
            "Primordial Blocks Map",
            "Shaped Acid Lakes Map",
            "Elder Lighthouse Map",
            "Elder Courthouse Map",
            "Shaped Peninsula Map",
            "Shaped Colonnade Map",
            "Elder Waste Pool Map",
            "Shaped Residence Map",
            "Shaped Wasteland Map",
            "Shaped Alleyways Map",
            "Elder Bone Crypt Map",
            "Elder Laboratory Map",
            "Elder Racecourse Map",
            "Elder Necropolis Map",
            "Shaped Courtyard Map",
            "Shaped Graveyard Map",
            "Elder Mud Geyser Map",
            "Shaped Mausoleum Map",
            "Elder Acid Lakes Map",
            "Overgrown Shrine Map",
            "Shaped Sepulchre Map",
            "Elder Ashen Wood Map",
            "Shaped Arid Lake Map",
            "Elder Excavation Map",
            "Shaped Waterways Map",
            "Shaped Promenade Map",
            "Underground Sea Map",
            "Elder Residence Map",
            "Shaped Precinct Map",
            "Elder Lava Lake Map",
            "Elder Promenade Map",
            "Haunted Mansion Map",
            "Shaped Tribunal Map",
            "Elder Arid Lake Map",
            "Elder Graveyard Map",
            "Primordial Pool Map",
            "Burial Chambers Map",
            "Elder Courtyard Map",
            "Elder Sepulchre Map",
            "Shaped Shipyard Map",
            "Torture Chamber Map",
            "Elder Peninsula Map",
            "Tropical Island Map",
            "Elder Waterways Map",
            "Shaped Cemetery Map",
            "Infested Valley Map",
            "Elder Wasteland Map",
            "Elder Mausoleum Map",
            "Elder Colosseum Map",
            "Shaped Ramparts Map",
            "Elder Colonnade Map",
            "Elder Alleyways Map",
            "Shaped Gardens Map",
            "Shaped Lookout Map",
            "Phantasmagoria Map",
            "Shaped Thicket Map",
            "Crimson Temple Map",
            "Shaped Arsenal Map",
            "Elder Basilica Map",
            "Shaped Orchard Map",
            "Relic Chambers Map",
            "Shaped Marshes Map",
            "Elder Ramparts Map",
            "Elder Shipyard Map",
            "Shaped Armoury Map",
            "Elder Tribunal Map",
            "Shaped Plateau Map",
            "Shaped Barrows Map",
            "Shaped Channel Map",
            "Shaped Springs Map",
            "Shaped Academy Map",
            "Shaped Factory Map",
            "Shaped Dungeon Map",
            "Shaped Chateau Map",
            "Shaped Iceberg Map",
            "Overgrown Ruin Map",
            "Elder Cemetery Map",
            "Shaped Glacier Map",
            "Shaped Estuary Map",
            "Shaped Volcano Map",
            "Shaped Leyline Map",
            "Elder Precinct Map",
            "Elder Iceberg Map",
            "Spider Forest Map",
            "Shaped Desert Map",
            "Shaped Belfry Map",
            "Elder Estuary Map",
            "Elder Arsenal Map",
            "Mineral Pools Map",
            "Elder Springs Map",
            "Elder Armoury Map",
            "Shaped Grotto Map",
            "Desert Spring Map",
            "Arachnid Nest Map",
            "Elder Channel Map",
            "Fungal Hollow Map",
            "Elder Terrace Map",
            "Elder Dungeon Map",
            "Elder Chateau Map",
            "Elder Academy Map",
            "Jungle Valley Map",
            "Elder Barrows Map",
            "Elder Factory Map",
            "Shaped Arcade Map",
            "Shaped Bazaar Map",
            "Shaped Canyon Map",
            "Shaped Ghetto Map",
            "Shaped Temple Map",
            "Elder Gardens Map",
            "Elder Glacier Map",
            "Elder Marshes Map",
            "Elder Lookout Map",
            "Shaped Museum Map",
            "Sulphur Vents Map",
            "Elder Leyline Map",
            "Elder Caldera Map",
            "Shaped Crater Map",
            "Elder Plateau Map",
            "Elder Carcass Map",
            "Shaped Strand Map",
            "Elder Orchard Map",
            "Shaped Fields Map",
            "Arachnid Tomb Map",
            "Elder Volcano Map",
            "Elder Thicket Map",
            "Shaped Cells Map",
            "Elder Ghetto Map",
            "Shaped Vault Map",
            "Shaped Siege Map",
            "Vaal Pyramid Map",
            "Elder Palace Map",
            "Acid Caverns Map",
            "Elder Crater Map",
            "Shaped Beach Map",
            "Shaped Wharf Map",
            "Shaped Arena Map",
            "Lava Chamber Map",
            "Elder Strand Map",
            "Shaped Shore Map",
            "Elder Desert Map",
            "Elder Bazaar Map",
            "Shaped Plaza Map",
            "Castle Ruins Map",
            "Shaped Coves Map",
            "Elder Summit Map",
            "Malformation Map",
            "Ivory Temple Map",
            "Shaped Villa Map",
            "Elder Canyon Map",
            "Shaped Dunes Map",
            "Shaped Tower Map",
            "Flooded Mine Map",
            "Elder Belfry Map",
            "Shaped Gorge Map",
            "Elder Arcade Map",
            "Shaped Geode Map",
            "Cursed Crypt Map",
            "Elder Grotto Map",
            "Ancient City Map",
            "Shaped Atoll Map",
            "Elder Museum Map",
            "Elder Fields Map",
            "Elder Shrine Map",
            "Conservatory Map",
            "Elder Temple Map",
            "Elder Wharf Map",
            "Shaped Mesa Map",
            "Toxic Sewer Map",
            "Elder Plaza Map",
            "Elder Siege Map",
            "Shaped Reef Map",
            "Elder Villa Map",
            "Shaped Port Map",
            "Elder Tower Map",
            "Coral Ruins Map",
            "Elder Dunes Map",
            "Elder Coves Map",
            "Spider Lair Map",
            "Sunken City Map",
            "Elder Cells Map",
            "Elder Shore Map",
            "Scriptorium Map",
            "Elder Geode Map",
            "Moon Temple Map",
            "Shaped Cage Map",
            "Crystal Ore Map",
            "Shaped Maze Map",
            "Elder Vault Map",
            "Elder Arena Map",
            "Elder Atoll Map",
            "Elder Beach Map",
            "Dark Forest Map",
            "Shaped Pier Map",
            "Vaal Temple Map",
            "Elder Gorge Map",
            "City Square Map",
            "Elder Pier Map",
            "Elder Core Map",
            "Lighthouse Map",
            "Necropolis Map",
            "Shaped Pit Map",
            "Acid Lakes Map",
            "Elder Lair Map",
            "Bone Crypt Map",
            "Elder Maze Map",
            "Elder Port Map",
            "Shaped Pen Map",
            "Waste Pool Map",
            "Excavation Map",
            "Laboratory Map",
            "Elder Mesa Map",
            "Elder Cage Map",
            "Ashen Wood Map",
            "Elder Reef Map",
            "Racecourse Map",
            "Mud Geyser Map",
            "Elder Park Map",
            "Courthouse Map",
            "Shaped Bog Map",
            "Elder Pen Map",
            "Waterways Map",
            "Sepulchre Map",
            "Lava Lake Map",
            "Wasteland Map",
            "Courtyard Map",
            "Elder Bog Map",
            "Peninsula Map",
            "Arid Lake Map",
            "Colonnade Map",
            "Residence Map",
            "Colosseum Map",
            "Graveyard Map",
            "Mausoleum Map",
            "Elder Pit Map",
            "Promenade Map",
            "Alleyways Map",
            "Shipyard Map",
            "Precinct Map",
            "Cemetery Map",
            "Tribunal Map",
            "Basilica Map",
            "Ramparts Map",
            "Armoury Map",
            "Carcass Map",
            "Plateau Map",
            "Factory Map",
            "Academy Map",
            "Barrows Map",
            "Thicket Map",
            "Chateau Map",
            "Terrace Map",
            "Channel Map",
            "Arsenal Map",
            "Dungeon Map",
            "Glacier Map",
            "Estuary Map",
            "Springs Map",
            "Gardens Map",
            "Marshes Map",
            "Caldera Map",
            "Lookout Map",
            "Leyline Map",
            "Iceberg Map",
            "Volcano Map",
            "Orchard Map",
            "Bazaar Map",
            "Fields Map",
            "Desert Map",
            "Crater Map",
            "Canyon Map",
            "Arcade Map",
            "Grotto Map",
            "Museum Map",
            "Shrine Map",
            "Belfry Map",
            "Strand Map",
            "Palace Map",
            "Ghetto Map",
            "Summit Map",
            "Temple Map",
            "Siege Map",
            "Shore Map",
            "Villa Map",
            "Arena Map",
            "Geode Map",
            "Plaza Map",
            "Cells Map",
            "Dunes Map",
            "Vault Map",
            "Atoll Map",
            "Beach Map",
            "Wharf Map",
            "Coves Map",
            "Gorge Map",
            "Tower Map",
            "Mesa Map",
            "Park Map",
            "Cage Map",
            "Maze Map",
            "Reef Map",
            "Core Map",
            "Lair Map",
            "Pier Map",
            "Port Map",
            "Pen Map",
            "Bog Map",
            "Pit Map",
            "Dig"
    };

    public static final UniqueBaseMap[] uniqueBaseMaps = {
            new UniqueBaseMap("Vaults of Atziri",               "Vaal Pyramid Map",         3),
            new UniqueBaseMap("Oba's Cursed Trove",             "Underground Sea Map",      3),
            new UniqueBaseMap("Caer Blaidd, Wolfpack's Den",    "Underground River Map",    3),
            new UniqueBaseMap("Oba's Cursed Trove",             "Torture Chamber Map",      3),
            new UniqueBaseMap("Poorjoy's Asylum",               "Temple Map",               3),
            new UniqueBaseMap("Whakawairua Tuahu",              "Strand Map",               3),
            new UniqueBaseMap("Mao Kun",                        "Shore Map",                3),
            new UniqueBaseMap("Mao Kun",                        "Reef Map",                 3),
            new UniqueBaseMap("Hall of Grandmasters",           "Promenade Map",            3),
            new UniqueBaseMap("Oba's Cursed Trove",             "Primordial Blocks Map",    3),
            new UniqueBaseMap("Acton's Nightmare",              "Overgrown Shrine Map",     3),
            new UniqueBaseMap("Death and Taxes",                "Necropolis Map",           3),
            new UniqueBaseMap("The Putrid Cloister",            "Museum Map",               3),
            new UniqueBaseMap("The Twilight Temple",            "Moon Temple Map",          3),
            new UniqueBaseMap("Doryani's Machinarium",          "Maze Map",                 3),
            new UniqueBaseMap("Olmec's Sanctum",                "Maze Map",                 3),
            new UniqueBaseMap("The Beachhead",                  "Harbinger Map",            3),
            new UniqueBaseMap("Hallowed Ground",                "Graveyard Map",            3),
            new UniqueBaseMap("Pillars of Arun",                "Dunes Map",                3),
            new UniqueBaseMap("The Coward's Trial",             "Cursed Crypt Map",         3),
            new UniqueBaseMap("The Vinktar Square",             "Courtyard Map",            3),
            new UniqueBaseMap("The Perandus Manor",             "Chateau Map",              3),
            new UniqueBaseMap("The Perandus Manor",             "Chateau Map",              9),
            new UniqueBaseMap("Hallowed Ground",                "Cemetery Map",             3),
            new UniqueBaseMap("Olmec's Sanctum",                "Bone Crypt Map",           3),
            new UniqueBaseMap("Maelström of Chaos",             "Atoll Map",                3)
    };


    public static class UniqueBaseMap {
        public String name, type;
        public int frame;

        public UniqueBaseMap(String name, String type, int frame) {
            this.name = name;
            this.type = type;
            this.frame = frame;
        }
    }
}
