package poe.Managers.Stat;

public enum StatType {
    TIME_CYCLE_TOTAL,
    TIME_CALC_PRICES,
    TIME_CALC_EXALT,
    TIME_REPLY_DOWNLOAD,
    TIME_PARSE_REPLY,
    TIME_UPLOAD_ACCOUNTS,
    TIME_RESET_STASHES,
    TIME_UPLOAD_ENTRIES,
    TIME_UPLOAD_USERNAMES,

    TIME_CYCLE_LEAGUES,

    COUNT_REPLY_SIZE,
    COUNT_API_CALLS,
    COUNT_TOTAL_STASHES,
    COUNT_TOTAL_ITEMS,
    COUNT_ACCEPTED_ITEMS,
    COUNT_ACTIVE_ACCOUNTS,

    TIME_CALC_COUNTERS,
    TIME_CALC_CURRENT,
    COUNT_DUPLICATE_JOB,

    APP_STARTUP,
    APP_SHUTDOWN,

    TIME_REMOVE_ENTRIES,
    TIME_ADD_DAILY,
    TIME_CALC_SPARK,
    TIME_ACCOUNT_CHANGES
}
